spring:
  application:
    name: spring-ai-openai-chat
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-3.5-turbo
        enabled: true

server:
  port: 8083
springdoc:
  api-docs:
    enabled: true